name: Spinnaker Pre Install
env:
  SPINNAKER_VERSION: 1.22.0
  REGISTRY_URL: "gcr.io/spinnaker-marketplace/"
  NEW_REGISTRY_URL: "registry.cn-beijing.aliyuncs.com/spinnaker-cd/"
  NEW_REGISTRY_URL2: "docker.io/spinnakercd/"
  TAG_FILE: "tagfile.txt"
  BOM_DIR: ".boms"

on:
  push:
    paths:
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: 01- Get bom file
      run: |
        docker pull registry.cn-beijing.aliyuncs.com/spinnaker-cd/halyard:1.32.0
        docker run -itd -p 8084:8084 -p 9000:9000 --name halyard  registry.cn-beijing.aliyuncs.com/spinnaker-cd/halyard:1.32.0
        sleep 5
        docker ps | grep halyard 
        chmod +x getbom.sh
        docker cp getbom.sh halyard:/opt/getbom.sh
        docker exec -u root halyard chmod +x /opt/getbom.sh
        docker exec -u root halyard sh /opt/getbom.sh ${SPINNAKER_VERSION}
        docker cp halyard:/opt/${SPINNAKER_VERSION}.yml ./${SPINNAKER_VERSION}.yml
        mkdir -p ${BOM_DIR}

    - name: 02- Get config file
      run: |
        python3 fileprocess.py ${SPINNAKER_VERSION}.yml  ${TAG_FILE} ${BOM_DIR} 
        tree ${BOM_DIR}
        # mkdir -p default/service-settings
        # for i in $(cat ${TAG_FILE}); do
        #   file_name=$(echo $i | awk -F ':' {'print$1'})
        #   echo "artifactId: gcr.azk8s.cn/spinnaker-marketplace/$i" > default/service-settings/$file_name.yml
        # done

    - name: 03- Collection files
      run : |
        sed -i "s#${SPINNAKER_VERSION}#SPIN_VERSION#g" install.sh
        mkdir -p artifacts/${SPINNAKER_VERSION}
        mv ${BOM_DIR} artifacts/${SPINNAKER_VERSION}/
        mkdir -p artifacts/${SPINNAKER_VERSION}/${BOM_DIR}/bom
        mv ${SPINNAKER_VERSION}.yml artifacts/${SPINNAKER_VERSION}/${BOM_DIR}/bom/ 
        # mv default artifacts/${SPINNAKER_VERSION}/
        mv halyard.yaml artifacts/${SPINNAKER_VERSION}/
        mv halyard.sh artifacts/${SPINNAKER_VERSION}/
        mv ${TAG_FILE} artifacts/${SPINNAKER_VERSION}/
        mv install.sh artifacts/${SPINNAKER_VERSION}/
    
    - uses: actions/upload-artifact@v2
      with: 
        name: Spinnaker-${{ env.SPINNAKER_VERSION }}
        path: artifacts/*    